# -*- coding: utf-8 -*-
"""superstore.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yw2y0WY-xyMmRVz8UYbw_1h7SHUy8e_y
"""

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from scipy import stats
from google.colab import files

# Load the dataset
file_name = "samplesuperstore - samplesuperstore.csv"
path = f"/content/{file_name}"

if not os.path.exists(path):
    print(f"The file '{file_name}' was not found at '{path}'. Please upload it.")
    uploaded = files.upload()
    if file_name not in uploaded:
        print(f"Warning: '{file_name}' was not found among the uploaded files. Please ensure you uploaded the correct file.")
    else:
        print(f"File '{file_name}' uploaded successfully.")
else:
    print(f"File '{file_name}' already exists at '{path}'.")

df = pd.read_csv(path)

# Display first 5 rows
print(df.head())

# Display dataset information
print(df.info())

# Check for missing values
print(df.isnull().sum())

# Average Sales
print("Average Sales:", np.mean(df["Sales"]))

# Sales by Category
sales = df.groupby("Category")["Sales"].sum()
print(sales)

# Bar Chart
plt.figure(figsize=(6,4))
plt.bar(sales.index, sales.values)
plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Sales")
plt.show()

# Scatter Plot
plt.figure(figsize=(6,4))
sns.scatterplot(data=df, x="Sales", y="Profit")
plt.title("Sales vs Profit")
plt.show()

# Train-Test Split
X_train, X_test = train_test_split(df, test_size=0.2, random_state=42)

print("Training Rows:", len(X_train))
print("Testing Rows:", len(X_test))

# Mean Sales using scipy
print("Mean Sales:", stats.tmean(df["Sales"]))