"""
read_binary_logs.py
-------------------
Reads a binary partition file generated by the Shopsy Log Aggregation
Engine and decodes it into human-readable log records.

This demonstrates that the binary (.bin) files contain structured
Shopsy log data and can be successfully recovered.

Usage:
    python read_binary_logs.py partitions/shopsy-chennai_ERROR.bin
"""

import struct
import sys

# Severity level mapping
LEVEL_CODE = {
    "DEBUG": 0,
    "INFO": 1,
    "WARNING": 2,
    "ERROR": 3
}

CODE_LEVEL = {v: k for k, v in LEVEL_CODE.items()}


def read_records(filepath):
    """Read and decode binary Shopsy log records."""

    with open(filepath, "rb") as file:
        data = file.read()

    offset = 0
    records = []

    while offset < len(data):

        # Read record length (4 bytes)
        (record_length,) = struct.unpack_from("!I", data, offset)
        offset += 4

        # Read complete record
        record = data[offset:offset + record_length]
        offset += record_length

        # Decode header
        timestamp_bytes, level_byte, service_length = struct.unpack_from(
            "!19sBH", record, 0
        )

        position = 19 + 1 + 2

        # Decode region/service name
        service = record[position:position + service_length].decode("utf-8")
        position += service_length

        # Decode message length
        (message_length,) = struct.unpack_from("!H", record, position)
        position += 2

        # Decode message
        message = record[position:position + message_length].decode("utf-8")

        records.append({
            "timestamp": timestamp_bytes.decode("ascii").strip(),
            "level": CODE_LEVEL[level_byte],
            "service": service,
            "message": message
        })

    return records


if __name__ == "__main__":

    if len(sys.argv) != 2:
        print("Usage:")
        print("python read_binary_logs.py partitions/shopsy-chennai_ERROR.bin")
        sys.exit(1)

    filepath = sys.argv[1]

    logs = read_records(filepath)

    print("=" * 65)
    print("Shopsy Binary Log Reader")
    print("=" * 65)
    print(f"Partition File : {filepath}")
    print(f"Total Records  : {len(logs)}")
    print("=" * 65)

    for log in logs:
        print(
            f"{log['timestamp']} | "
            f"{log['level']} | "
            f"{log['service']} | "
            f"{log['message']}"
        )